name: update

on:
  schedule:
    # run this every two hours
    - cron:  '0 */2 * * *'

jobs:
  updater:
    if: github.repository == 'bedrock-dot-dev/docs'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Setup git environment
        run: |
          git config --global user.name 'destruc7i0n'
          git config --global user.email 'destruc7i0n@users.noreply.github.com'
      - run: yarn
      - name: Check for bedrock docs update
        id: docs-updated
        working-directory: scripts
        run: |
          output="$(yarn -s check-update)"
          echo "::set-output name=result::$output"
          echo "$output"
      - name: Push to GitHub
        if: ${{ fromJSON(steps.docs-updated.outputs.result).error == 'false' && fromJSON(steps.docs-updated.outputs.result).update != 'false' }}
        env:
          DOCS_VERSION: ${{ fromJSON(steps.docs-updated.outputs.result).update }}
          VERCEL_DEPLOY_HOOK: ${{ secrets.VERCEL_DEPLOY_HOOK }}
        run: |
          git add --all
          git commit -m "Docs update: $DOCS_VERSION"
          git push
          sleep 1m
          curl -X POST $VERCEL_DEPLOY_HOOK
